# coding: utf-8

"""
    IamBackoffice Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from iambackoffice.models.iambackoffice_search_groups_response import IambackofficeSearchGroupsResponse

class TestIambackofficeSearchGroupsResponse(unittest.TestCase):
    """IambackofficeSearchGroupsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IambackofficeSearchGroupsResponse:
        """Test IambackofficeSearchGroupsResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IambackofficeSearchGroupsResponse`
        """
        model = IambackofficeSearchGroupsResponse()
        if include_optional:
            return IambackofficeSearchGroupsResponse(
                groups = [
                    iambackoffice.models.iambackoffice_group.iambackofficeGroup(
                        id = '', )
                    ]
            )
        else:
            return IambackofficeSearchGroupsResponse(
        )
        """

    def testIambackofficeSearchGroupsResponse(self):
        """Test IambackofficeSearchGroupsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
