# coding: utf-8

"""
    IamBackoffice Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from iambackoffice.models.iambackoffice_unassign_roles_response import IambackofficeUnassignRolesResponse

class TestIambackofficeUnassignRolesResponse(unittest.TestCase):
    """IambackofficeUnassignRolesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IambackofficeUnassignRolesResponse:
        """Test IambackofficeUnassignRolesResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IambackofficeUnassignRolesResponse`
        """
        model = IambackofficeUnassignRolesResponse()
        if include_optional:
            return IambackofficeUnassignRolesResponse(
                role_codes = [
                    ''
                    ]
            )
        else:
            return IambackofficeUnassignRolesResponse(
        )
        """

    def testIambackofficeUnassignRolesResponse(self):
        """Test IambackofficeUnassignRolesResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
