# coding: utf-8

"""
    IamBackoffice Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from iambackoffice.models.iambackoffice_device import IambackofficeDevice

class TestIambackofficeDevice(unittest.TestCase):
    """IambackofficeDevice unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IambackofficeDevice:
        """Test IambackofficeDevice
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IambackofficeDevice`
        """
        model = IambackofficeDevice()
        if include_optional:
            return IambackofficeDevice(
                description = '',
                name = '',
                device_type = ''
            )
        else:
            return IambackofficeDevice(
        )
        """

    def testIambackofficeDevice(self):
        """Test IambackofficeDevice"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
