# coding: utf-8

"""
    IamBackoffice Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from iambackoffice.api.iam_backoffice_api import IamBackofficeApi


class TestIamBackofficeApi(unittest.TestCase):
    """IamBackofficeApi unit test stubs"""

    def setUp(self) -> None:
        self.api = IamBackofficeApi()

    def tearDown(self) -> None:
        pass

    def test_iam_backoffice_assign_roles(self) -> None:
        """Test case for iam_backoffice_assign_roles

        AUTHZ
        """
        pass

    def test_iam_backoffice_assign_user_to_group(self) -> None:
        """Test case for iam_backoffice_assign_user_to_group

        """
        pass

    def test_iam_backoffice_create_group(self) -> None:
        """Test case for iam_backoffice_create_group

        GROUPS
        """
        pass

    def test_iam_backoffice_disable_user_mfa(self) -> None:
        """Test case for iam_backoffice_disable_user_mfa

        """
        pass

    def test_iam_backoffice_enable_user_mfa(self) -> None:
        """Test case for iam_backoffice_enable_user_mfa

        """
        pass

    def test_iam_backoffice_generate_secret_for_qr(self) -> None:
        """Test case for iam_backoffice_generate_secret_for_qr

        MFA
        """
        pass

    def test_iam_backoffice_get_user(self) -> None:
        """Test case for iam_backoffice_get_user

        USER
        """
        pass

    def test_iam_backoffice_login(self) -> None:
        """Test case for iam_backoffice_login

        LOGIN
        """
        pass

    def test_iam_backoffice_login_mfa(self) -> None:
        """Test case for iam_backoffice_login_mfa

        LOGIN MFA
        """
        pass

    def test_iam_backoffice_logout(self) -> None:
        """Test case for iam_backoffice_logout

        """
        pass

    def test_iam_backoffice_register(self) -> None:
        """Test case for iam_backoffice_register

        REGISTRATION
        """
        pass

    def test_iam_backoffice_search_groups(self) -> None:
        """Test case for iam_backoffice_search_groups

        """
        pass

    def test_iam_backoffice_unassign_roles(self) -> None:
        """Test case for iam_backoffice_unassign_roles

        """
        pass


if __name__ == '__main__':
    unittest.main()
