# coding: utf-8

"""
    IamBackoffice Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from iambackoffice.models.iambackoffice_login_request import IambackofficeLoginRequest

class TestIambackofficeLoginRequest(unittest.TestCase):
    """IambackofficeLoginRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IambackofficeLoginRequest:
        """Test IambackofficeLoginRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IambackofficeLoginRequest`
        """
        model = IambackofficeLoginRequest()
        if include_optional:
            return IambackofficeLoginRequest(
                tenant_id = '',
                ip_address = '',
                login_id = '',
                meta_data = iambackoffice.models.iambackoffice_meta_data.iambackofficeMetaData(
                    device = iambackoffice.models.iambackoffice_device.iambackofficeDevice(
                        description = '', 
                        name = '', 
                        device_type = '', ), ),
                no_tokens = True,
                password = '',
                two_factor_trust_id = ''
            )
        else:
            return IambackofficeLoginRequest(
        )
        """

    def testIambackofficeLoginRequest(self):
        """Test IambackofficeLoginRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
