# coding: utf-8

"""
    IamBackoffice Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictStr
from pydantic import Field
from iambackoffice.models.iambackoffice_two_factor_method import IambackofficeTwoFactorMethod
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class IambackofficeUserTwoFactorConfiguration(BaseModel):
    """
    IambackofficeUserTwoFactorConfiguration
    """ # noqa: E501
    methods: Optional[List[IambackofficeTwoFactorMethod]] = None
    recovery_codes: Optional[List[StrictStr]] = Field(default=None, alias="recoveryCodes")
    __properties: ClassVar[List[str]] = ["methods", "recoveryCodes"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of IambackofficeUserTwoFactorConfiguration from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in methods (list)
        _items = []
        if self.methods:
            for _item in self.methods:
                if _item:
                    _items.append(_item.to_dict())
            _dict['methods'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of IambackofficeUserTwoFactorConfiguration from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "methods": [IambackofficeTwoFactorMethod.from_dict(_item) for _item in obj.get("methods")] if obj.get("methods") is not None else None,
            "recoveryCodes": obj.get("recoveryCodes")
        })
        return _obj


