# coding: utf-8

"""
    IamBackoffice Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from iambackoffice.models.iambackoffice_two_factor_method import IambackofficeTwoFactorMethod
from iambackoffice.models.iambackoffice_user import IambackofficeUser
from iambackoffice.models.protobuf_any import ProtobufAny
from typing import Optional, Set
from typing_extensions import Self

class IambackofficeLoginResponse(BaseModel):
    """
    IambackofficeLoginResponse
    """ # noqa: E501
    tokens: Optional[ProtobufAny] = None
    user: Optional[IambackofficeUser] = None
    methods: Optional[List[IambackofficeTwoFactorMethod]] = None
    two_factor_id: Optional[StrictStr] = Field(default=None, alias="twoFactorId")
    tenant_id: Optional[StrictStr] = Field(default=None, alias="tenantId")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["tokens", "user", "methods", "twoFactorId", "tenantId"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of IambackofficeLoginResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of tokens
        if self.tokens:
            _dict['tokens'] = self.tokens.to_dict()
        # override the default output from pydantic by calling `to_dict()` of user
        if self.user:
            _dict['user'] = self.user.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in methods (list)
        _items = []
        if self.methods:
            for _item_methods in self.methods:
                if _item_methods:
                    _items.append(_item_methods.to_dict())
            _dict['methods'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of IambackofficeLoginResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "tokens": ProtobufAny.from_dict(obj["tokens"]) if obj.get("tokens") is not None else None,
            "user": IambackofficeUser.from_dict(obj["user"]) if obj.get("user") is not None else None,
            "methods": [IambackofficeTwoFactorMethod.from_dict(_item) for _item in obj["methods"]] if obj.get("methods") is not None else None,
            "twoFactorId": obj.get("twoFactorId"),
            "tenantId": obj.get("tenantId")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


